"""Initial migration.

Revision ID: 6440dca24971
Revises: a658d7339118
Create Date: 2024-08-23 11:53:34.323968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6440dca24971'
down_revision = 'a658d7339118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('food')
    op.drop_table('goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=False),
    sa.Column('protein', sa.INTEGER(), nullable=False),
    sa.Column('carbs', sa.INTEGER(), nullable=False),
    sa.Column('fat', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('caloric_value', sa.FLOAT(), nullable=False),
    sa.Column('fat', sa.FLOAT(), nullable=False),
    sa.Column('saturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('monounsaturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('polyunsaturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('carbohydrates', sa.FLOAT(), nullable=False),
    sa.Column('sugars', sa.FLOAT(), nullable=False),
    sa.Column('protein', sa.FLOAT(), nullable=False),
    sa.Column('dietary_fiber', sa.FLOAT(), nullable=False),
    sa.Column('cholesterol', sa.FLOAT(), nullable=False),
    sa.Column('sodium', sa.FLOAT(), nullable=False),
    sa.Column('water', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_a', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b1', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b11', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b12', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b2', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b3', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b5', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b6', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_c', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_d', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_e', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_k', sa.FLOAT(), nullable=False),
    sa.Column('calcium', sa.FLOAT(), nullable=False),
    sa.Column('copper', sa.FLOAT(), nullable=False),
    sa.Column('iron', sa.FLOAT(), nullable=False),
    sa.Column('magnesium', sa.FLOAT(), nullable=False),
    sa.Column('manganese', sa.FLOAT(), nullable=False),
    sa.Column('phosphorus', sa.FLOAT(), nullable=False),
    sa.Column('potassium', sa.FLOAT(), nullable=False),
    sa.Column('selenium', sa.FLOAT(), nullable=False),
    sa.Column('zinc', sa.FLOAT(), nullable=False),
    sa.Column('nutrition_density', sa.FLOAT(), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
