"""Update database schema

Revision ID: 6b0e04d9f711
Revises: 9a8d8e95d2db
Create Date: 2024-08-25 09:58:28.192305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6b0e04d9f711'
down_revision = '9a8d8e95d2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    op.drop_table('food')
    op.drop_table('diet_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=150), nullable=False),
    sa.Column('diet_plan', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('caloric_value', sa.FLOAT(), nullable=False),
    sa.Column('fat', sa.FLOAT(), nullable=False),
    sa.Column('saturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('monounsaturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('polyunsaturated_fats', sa.FLOAT(), nullable=False),
    sa.Column('carbohydrates', sa.FLOAT(), nullable=False),
    sa.Column('sugars', sa.FLOAT(), nullable=False),
    sa.Column('protein', sa.FLOAT(), nullable=False),
    sa.Column('dietary_fiber', sa.FLOAT(), nullable=False),
    sa.Column('cholesterol', sa.FLOAT(), nullable=False),
    sa.Column('sodium', sa.FLOAT(), nullable=False),
    sa.Column('water', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_a', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b1', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b11', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b12', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b2', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b3', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b5', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_b6', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_c', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_d', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_e', sa.FLOAT(), nullable=False),
    sa.Column('vitamin_k', sa.FLOAT(), nullable=False),
    sa.Column('calcium', sa.FLOAT(), nullable=False),
    sa.Column('copper', sa.FLOAT(), nullable=False),
    sa.Column('iron', sa.FLOAT(), nullable=False),
    sa.Column('magnesium', sa.FLOAT(), nullable=False),
    sa.Column('manganese', sa.FLOAT(), nullable=False),
    sa.Column('phosphorus', sa.FLOAT(), nullable=False),
    sa.Column('potassium', sa.FLOAT(), nullable=False),
    sa.Column('selenium', sa.FLOAT(), nullable=False),
    sa.Column('zinc', sa.FLOAT(), nullable=False),
    sa.Column('nutrition_density', sa.FLOAT(), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=False),
    sa.Column('protein', sa.INTEGER(), nullable=False),
    sa.Column('carbs', sa.INTEGER(), nullable=False),
    sa.Column('fat', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
