"""Add bmi_category to Goal model

Revision ID: e7ca00ec9919
Revises: 6b0e04d9f711
Create Date: 2024-08-26 21:00:42.136811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ca00ec9919'
down_revision = '6b0e04d9f711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('diet_plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('caloric_value', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('saturated_fats', sa.Float(), nullable=False),
    sa.Column('monounsaturated_fats', sa.Float(), nullable=False),
    sa.Column('polyunsaturated_fats', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('sugars', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('dietary_fiber', sa.Float(), nullable=False),
    sa.Column('cholesterol', sa.Float(), nullable=False),
    sa.Column('sodium', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('vitamin_a', sa.Float(), nullable=False),
    sa.Column('vitamin_b1', sa.Float(), nullable=False),
    sa.Column('vitamin_b11', sa.Float(), nullable=False),
    sa.Column('vitamin_b12', sa.Float(), nullable=False),
    sa.Column('vitamin_b2', sa.Float(), nullable=False),
    sa.Column('vitamin_b3', sa.Float(), nullable=False),
    sa.Column('vitamin_b5', sa.Float(), nullable=False),
    sa.Column('vitamin_b6', sa.Float(), nullable=False),
    sa.Column('vitamin_c', sa.Float(), nullable=False),
    sa.Column('vitamin_d', sa.Float(), nullable=False),
    sa.Column('vitamin_e', sa.Float(), nullable=False),
    sa.Column('vitamin_k', sa.Float(), nullable=False),
    sa.Column('calcium', sa.Float(), nullable=False),
    sa.Column('copper', sa.Float(), nullable=False),
    sa.Column('iron', sa.Float(), nullable=False),
    sa.Column('magnesium', sa.Float(), nullable=False),
    sa.Column('manganese', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('selenium', sa.Float(), nullable=False),
    sa.Column('zinc', sa.Float(), nullable=False),
    sa.Column('nutrition_density', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.String(length=20), nullable=True),
    sa.Column('bmi_category', sa.String(length=20), nullable=True),
    sa.Column('fitness_level', sa.String(length=20), nullable=True),
    sa.Column('health_issues', sa.Text(), nullable=True),
    sa.Column('veg_preference', sa.String(length=10), nullable=True),
    sa.Column('weight_goal', sa.String(length=10), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    op.drop_table('food')
    op.drop_table('diet_plan')
    # ### end Alembic commands ###
